
import * as React from "react" ;







export const metadata = {
  title: 'StuDK',
  description: 'StuDK. (App Generated by Next.js)',
}

function renderPictureCard(...[{ titleElem, contents, }] : [{ titleElem: React.ReactElement | string, contents: React.ReactElement | null, }])
{
  ;

  return (
    <studk-card style={{ }} >
      { titleElem }
      { contents }
    </studk-card>
  ) ;
}

import "@/components/jsxStudkCard" ;

// import type { JSX as JSX0 , } from "react"; ;
// import type { JSX, } from "react/jsx-runtime"; ;

export default function App()
{
  ;

  const c = (
    <div>
      <h1>
        This is StuDK
      </h1>
      <p>
        This is
        a demo app
        developed to demonstrate various applets building on StuDK.
      </p>
      <ul>
      <li>
        <Link href="/iaud" >
          { renderPictureCard({
            titleElem: (
              <p>
                The StuDK Audio Pipeline Demo App Screenshot
              </p>
            ) ,
            contents: (
              <Image
              alt="The StuDK Audio Pipeline Demo App Screenshot"
              src={iIAudAppScreenshotUrl }
              width={250}
              height={250}
              priority={false}
              />
            ) ,
          }) }
        </Link>
      </li>
      <li>
        <Link href="/i3d" >
          <p>
          I3D (unfinished)
          </p>
        </Link>
      </li>
      </ul>
      <p>
        <q>
        This is StuDK!
        </q>
      </p>
    </div>
  ) ;
  return (
    <div style={{ display: "block flow-root", paddingBlock: "2em 3em", paddingInline: "1em 3em", minBlockSize: "45em" }} >
        { c }
    </div>
  ) ;
} ;

import iIAudAppScreenshotUrl from "@/components/spcl/IAudAppScreenshot.png" ;




import dynamicComponent from "next/dynamic";

import Link from "next/link";

import Image from "next/image";




import JsxLivingroomCornerBallFigure from "@/components/jsxLivingroomCornerBallFigure" ;








