name: Test Everything Including Stuffs Still Negative

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Everything Including Stuffs Still Negative
      run: |
        npm ci
        # npm install

        npm run test
        
        cd packages/typexpe-commons
        npm run test
        cd ../../
        
        tsc --build 
        
        npm run test
        
        cd packages/typexpe-commons
        npm run test
        cd ../../



